name: AndroidBuild

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        run : chmod +x ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: AndroidBuild.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1
